name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: colivmanager-backend
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build Docker image
      run: |
        IMAGE="${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ secrets.ARTIFACT_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
        docker build -t "$IMAGE" .
        echo "IMAGE=$IMAGE" >> $GITHUB_ENV

    - name: Push to Artifact Registry
      run: |
        gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev --quiet
        docker push "$IMAGE"

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy colivmanager-backend \
          --image "$IMAGE" \
          --region "${{ secrets.REGION }}" \
          --platform managed \
          --allow-unauthenticated
