name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: coliv-backend
  REGION: asia-south1
  SERVICE: colivmanager-backend
  REPO: colivmanager-repo
  IMAGE: colivmanager-backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build and push Docker image
        run: |
          gcloud auth configure-docker ${REGION}-docker.pkg.dev --quiet
          docker build -t ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/${IMAGE}:$GITHUB_SHA .
          docker push ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/${IMAGE}:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${SERVICE} \
            --image ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/${IMAGE}:$GITHUB_SHA \
            --region ${REGION} \
            --platform managed \
            --allow-unauthenticated \
            --port 8080
